# Generated by Django 4.0.5 on 2022-06-09 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('expiry_date', models.DateTimeField()),
                ('is_redeemed', models.BooleanField(default=False)),
                ('discount_type', models.CharField(choices=[('percentage', '%'), ('value', '$')], max_length=50)),
                ('discount_value', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
